### ISSUE TITLE
Kernal crash with windows

### ISSUE THREAD

**Issue by anthony-chaudhary** [udacity/CarND-LeNet-Lab#12]
Hello,

The code provided in the solution file will not run on a windows GPU enabled machine. Jupyter notebook crashes and gives non-useful error message. Running in normal python build yields the error: CUDA_ERROR_ILLEGAL_ADDRESS. This can be solved as suggested here: https://carnd-forums.udacity.com/questions/32717096/tensorflow-gpu-error-cudaerrorillegaladdress

For this instance, in[7] this works:
```
with tf.device('/cpu:0'):
	one_hot_y = tf.one_hot(y, 10)
```

As it can be a frustrating error, and jupyter gives no useful feedback, suggest offering this fix in the readme comments, or even updating the code until CUDA/tensorflow fix it properly.

Anthony

**Comment by akshaybabloo** [comment]
Have you tried putting the code in a Python file and check it? because it works for me.

**Comment by mvirgo** [comment]
Looks like no further issues with this, so closing, plus this will be hosted in-classroom soon.
